name: Deploy Theme to The Bubble

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Droplet and Pull Changes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          port: ${{ secrets.DO_PORT }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /var/www/html/www.thebubble.org.uk/wp-content/themes/thebubble
            git config --global --add safe.directory /var/www/html/www.thebubble.org.uk/wp-content/themes/thebubble
            git pull origin main || git pull origin master